### ISSUE TITLE
Get in touch not working

### ISSUE THREAD

**Issue by somshot** [rampatra/photography#25]
When I send the message, it shows 405 Not allowed. Could you please help in setting it up so the emails come to me.
https://somshot.github.io/photos/

**Comment by rampatra** [comment]
You have to follow the instructions given in the readme file to make it work.
```
Contact Form
You can make the contact form work without the need of any server-side code. Just follow this article on github which uses a simple google script to send emails or to upload to a google spreadsheet when someone submits the form.
```
