### ISSUE TITLE
Compiling SASS files

### ISSUE THREAD

**Issue by leoseccia** [rampatra/photography#67]
Hello @rampatra ,

This theme is lovely. Thank you for sharing.

Any ideas why `bundle exec jekyll serve` and `bundle exec jekyll build` don't recompile the SASS (i.e. update the CSS files)?

Thanks.

Leo

**Comment by rampatra** [comment]
Because these commands are related to Jekyll and not for compiling CSS. For compiling CSS, I have used gulp. You can use gulp or any other tool you want.

**Comment by leoseccia** [comment]
Ah ok...

Jekyll got its own SASS converter: https://jekyllrb.com/docs/assets/

**Comment by leoseccia** [comment]
#68
